apiVersion: apps/v1
kind: Deployment
metadata:
    name: core-v1
    namespace: istio-demo
    labels:
        app: core
        tier: backend
        version: v1
#        istio-injection: enabled
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    selector:
        matchLabels:
            app: core
            tier: backend
            version: v1
    template:
        metadata:
            labels:
                app: core
                tier: backend
                version: v1
        spec:
            serviceAccountName: core-service-account
            restartPolicy: Always
            containers:
            - name: core-v1
              image: core
              imagePullPolicy: "IfNotPresent"
              envFrom:
              - configMapRef:
                    name: core-configmap
              ports:
              - name: core-v1
                containerPort: 8000
            
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: core-v2
    namespace: istio-demo
    labels:
        app: core
        tier: backend
        version: v2
#        istio-injection: enabled
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    selector:
        matchLabels:
            app: core
            tier: backend
            version: v2
    template:
        metadata:
            labels:
                app: core
                tier: backend
                version: v2
        spec:
            serviceAccountName: core-service-account
            restartPolicy: Always
            containers:
            - name: core-v2
              image: core
              imagePullPolicy: "IfNotPresent"
              envFrom:
              - configMapRef:
                    name: core-configmap
              ports:
              - name: core-v2
                containerPort: 8000
            
