apiVersion: v1
kind: Service
metadata:
    name: core
    labels:
        app: core
        tier: backend
spec:
    type: LoadBalancer
    ports:
        - port: 8000
          targetPort: 8000
          protocol: TCP
    selector:
        app: core
        tier: backend
          