apiVersion: v1
kind: Service
metadata:
    name: daemon
    namespace: istio-demo
    labels:
        app: daemon
        tier: backend
spec:
    # type: LoadBalancer
    ports:
        - port: 7000
          targetPort: 7000
          name: tcp-daemon
          protocol: TCP
    selector:
        app: daemon
        tier: backend
          