apiVersion: apps/v1
kind: Deployment
metadata:
    name: daemon
    namespace: istio-demo
    labels:
        app: daemon
        tier: backend
#        istio-injection: enabled
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    selector:
        matchLabels:
            app: daemon
            tier: backend
    template:
        metadata:
            labels:
                app: daemon
                tier: backend
        spec:
            serviceAccountName: daemon-service-account
            restartPolicy: Always
            containers:
            - name: daemon
              image: daemon
              imagePullPolicy: "IfNotPresent"
              envFrom:
              - configMapRef:
                    name: daemon-configmap
              ports:
              - name: daemon
                containerPort: 7000
            
