apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
    namespace: istio-demo
    labels:
        app: postgres
        tier: db
#        istio-injection: enabled
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    selector:
        matchLabels:
            app: postgres
            tier: db
    template:
        metadata:
            labels:
                app: postgres
                tier: db
        spec:
            restartPolicy: Always
            containers:
            - name: postgres
              image: postgres:latest
              imagePullPolicy: "IfNotPresent"
              envFrom:
                - configMapRef:
                    name: postgres-config
              ports:
              - name: postgres
                containerPort: 5432
            