apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: istio-demo
  labels:
    app: postgres
    tier: db
spec:
    # type: NodePort
    ports:
    - port: 5432
      targetPort: 5432
      name: tcp-postgres
      protocol: TCP
    selector:
      app: postgres
      tier: db