apiVersion: v1
kind: Service
metadata:
    name: core
    namespace: istio-demo
    labels:
        app: core
        tier: backend
spec:
    # type: LoadBalancer
    ports:
        - port: 8000
          targetPort: 8000
          name: tcp-core
          protocol: TCP
    selector:
        app: core
        tier: backend
          