apiVersion: v1
kind: Service
metadata:
    name: localstack
    namespace: istio-demo
    labels:
        app: localstack
        tier: queue
spec:
    # type: LoadBalancer
    ports:
    - port: 4566
      targetPort: 4566
      name: tcp-localstack
      protocol: TCP
    selector:
        app: localstack
        tier: queue