# apiVersion: install.istio.io/v1alpha1
# kind: IstioOperator
# metadata:
#   namespace: istio-system
#   name: istio-operator
# spec:
#   components:
#     ingressGateways:
#     - name: istio-ingressgateway
#       enabled: true
#       k8s:
#         service:
#           ports:
#           - name: http-status-port
#             port: 15021
#             targetPort: 15021
#           - name: http2
#             port: 80
#             targetPort: 8080
#           - name: https
#             port: 443
#             targetPort: 8443
#           - name: tcp-istiod
#             port: 15012
#             targetPort: 15012
#           - name: tls
#             port: 15443
#             targetPort: 15443
#           - name: http-core
#             port: 8000
#             targetPort: 8000
#           - name: http-daemon
#             port: 7000
#             targetPort: 7000
