kind: Gateway
apiVersion: networking.istio.io/v1beta1
metadata:
  name: test-gw
  namespace: istio-demo
spec:
  servers:
    - port:
        number: 8000
        protocol: HTTP
        name: http-core-test
      hosts:
        - '*'
      tls: {}
    - port:
        number: 7000
        protocol: HTTP
        name: http-daemon-test
      hosts:
        - '*'
      tls: {}
  selector:
    istio: ingressgateway
