# kind: VirtualService
# apiVersion: networking.istio.io/v1beta1
# metadata:
#   name: daemon
#   namespace: istio-demo
# spec:
#   hosts:
#     - daemon.istio-demo.svc.cluster.local
#   gateways:
#     - istio-demo/test-gw
#   http:
#     - route:
#         - destination:
#             host: daemon.istio-demo.svc.cluster.local
#           weight: 100
---
# kind: DestinationRule
# apiVersion: networking.istio.io/v1beta1
# metadata:
#   name: daemon
#   namespace: istio-demo
# spec:
#   host: daemon.istio-demo.svc.cluster.local
---
# kind: VirtualService
# apiVersion: networking.istio.io/v1beta1
# metadata:
#   name: core
#   namespace: istio-demo
# spec:
#   hosts:
#     - core.istio-demo.svc.cluster.local
#   gateways:
#     - istio-demo/test-gw
#   http:
#     - route:
#         - destination:
#             host: core.istio-demo.svc.cluster.local
#             subset: v1
#           weight: 30
#         - destination:
#             host: core.istio-demo.svc.cluster.local
#             subset: v2
#           weight: 70
---
# kind: DestinationRule
# apiVersion: networking.istio.io/v1beta1
# metadata:
#   name: core
#   namespace: istio-demo
# spec:
#   host: core.istio-demo.svc.cluster.local
#   subsets:
#     - name: v1
#       labels:
#         version: v1
#     - name: v2
#       labels:
#         version: v2

